const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC_RI = path.join(ROOT, 'ri');
const DIST = path.join(ROOT, 'dist');
const DIST_RI = path.join(DIST, 'ri');
const CONFIG_FILE = path.join(ROOT, 'config.json');

// Helper: Shuffle Array (Fisher-Yates)
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Main function
function build() {
    console.log('Starting build...');

    // Load Config
    let config = { domain: '' };
    
    // Priority 1: Environment Variable
    if (process.env.DOMAIN) {
        config.domain = process.env.DOMAIN;
        console.log('Loaded domain from environment variable.');
    } 
    // Priority 2: Config File
    else if (fs.existsSync(CONFIG_FILE)) {
        try {
            const configContent = fs.readFileSync(CONFIG_FILE, 'utf8');
            const parsed = JSON.parse(configContent);
            if (parsed.domain) {
                config.domain = parsed.domain;
            }
            console.log('Loaded domain from config.json.');
        } catch (e) {
            console.warn('Failed to parse config.json, using default settings.');
        }
    }

    // Normalize domain (remove trailing slash)
    if (config.domain) {
        config.domain = config.domain.replace(/\/$/, '');
    }

    console.log(`Using domain prefix: "${config.domain}"`);

    // 1. Clean/Create Dist
    if (fs.existsSync(DIST)) {
        fs.rmSync(DIST, { recursive: true, force: true });
    }
    fs.mkdirSync(DIST, { recursive: true });
    fs.mkdirSync(DIST_RI, { recursive: true });

    // 2. Process Folders
    const types = ['h', 'v'];
    
    types.forEach(type => {
        const srcFolder = path.join(SRC_RI, type);
        const distFolder = path.join(DIST_RI, type);
        
        if (!fs.existsSync(srcFolder)) {
            console.warn(`Source folder not found: ${srcFolder}`);
            return;
        }

        fs.mkdirSync(distFolder, { recursive: true });

        // Read and Filter Images
        let files = fs.readdirSync(srcFolder).filter(f => f.match(/\.(webp|jpg|jpeg|png|gif)$/i));
        
        // Shuffle
        files = shuffle(files);

        // Copy and Rename
        files.forEach((file, index) => {
            const srcPath = path.join(srcFolder, file);
            // User requested 1.webp, 2.webp, etc.
            const destPath = path.join(distFolder, `${index + 1}.webp`);
            fs.copyFileSync(srcPath, destPath);
        });

        const count = files.length;
        console.log(`Processed ${type}: ${count} images.`);

        // 3. Generate JS
        // The user wants a script that replaces a special link in an HTML form.
        // We will provide a function and an auto-runner.
        const jsContent = `
/**
 * Static Random Pic API - ${type.toUpperCase()} (Horizontal/Vertical)
 * Generated by build script
 */
(function() {
    var total = ${count};
    var type = '${type}';
    var domain = '${config.domain}';
    
    // Function to get a random URL
    function getRandomUrl() {
        var num = Math.floor(Math.random() * total) + 1;
        // Using configured domain + absolute path
        return domain + '/ri/' + type + '/' + num + '.webp';
    }

    // Expose global function
    window['getRandomPic' + type.toUpperCase()] = getRandomUrl;

    // Auto-replace logic
        // Global search and replace for the placeholder in all attributes and text nodes
        document.addEventListener('DOMContentLoaded', function() {
            var url = getRandomUrl();
            var placeholder = 'https://random:' + type;
            var regex = new RegExp(placeholder, 'g');
            
            // 1. Scan all elements and their attributes
            var allElements = document.getElementsByTagName('*');
            for (var i = 0; i < allElements.length; i++) {
                var el = allElements[i];
                // Skip script tags to avoid replacing source code if it happens to match (though unlikely in this context)
                if (el.tagName === 'SCRIPT') continue;

                var attributes = el.attributes;
                if (attributes) {
                    for (var j = 0; j < attributes.length; j++) {
                        var attr = attributes[j];
                        if (attr.value && attr.value.indexOf(placeholder) !== -1) {
                            attr.value = attr.value.replace(regex, url);
                        }
                    }
                }
            }

            // 2. Scan text nodes (including inside <style> tags)
            var rootNode = document.documentElement || document.body;
            if (rootNode) {
                var walker = document.createTreeWalker(rootNode, NodeFilter.SHOW_TEXT, null, false);
                var node;
                while (node = walker.nextNode()) {
                    // Skip if parent is script (but allow style)
                    if (node.parentNode && node.parentNode.tagName === 'SCRIPT') continue;
                    
                    if (node.nodeValue && node.nodeValue.indexOf(placeholder) !== -1) {
                        node.nodeValue = node.nodeValue.replace(regex, url);
                    }
                }
            }
            
            console.log('Random Pic ' + type.toUpperCase() + ' globally replaced placeholder: ' + placeholder);
        });
    })();
`;
        fs.writeFileSync(path.join(DIST, `random-${type}.js`), jsContent.trim());
    });

    // Copy index.html if exists and not empty
    const indexSrc = path.join(ROOT, 'index.html');
    if (fs.existsSync(indexSrc)) {
         const stats = fs.statSync(indexSrc);
         if (stats.size > 0) {
             fs.copyFileSync(indexSrc, path.join(DIST, 'index.html'));
             console.log('Copied index.html to dist');
         } else {
             console.log('index.html is empty, creating a demo page in dist...');
             createDemoHtml();
         }
    } else {
        createDemoHtml();
    }
    
    console.log('Build complete. Output is in /dist folder.');
}

function createDemoHtml() {
    const htmlContent = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Static Random Pic API Demo</title>
    <style>
        body { font-family: sans-serif; max-width: 800px; margin: 20px auto; padding: 20px; }
        .card { border: 1px solid #ccc; padding: 20px; margin-bottom: 20px; border-radius: 8px; }
        img { max-width: 100%; height: auto; border-radius: 4px; }
        .btn { display: inline-block; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
        .bg-box { width: 100%; height: 200px; background-size: cover; background-position: center; border-radius: 4px; border: 1px dashed #999; display: flex; align-items: center; justify-content: center; color: white; text-shadow: 0 1px 3px rgba(0,0,0,0.8); font-weight: bold; }
        
        /* CSS Variable Example in Style Tag */
        :root {
            --random-bg-h: url('https://random:h');
        }
        .css-var-box {
            width: 100%; height: 100px; 
            background-image: var(--random-bg-h);
            background-size: cover;
            border: 1px solid red;
            display: flex; align-items: center; justify-content: center; color: white; text-shadow: 0 1px 3px black;
        }
    </style>
</head>
<body>
    <h1>Static Random Pic API (Client-Side)</h1>
    <p>This is a static implementation. Images are randomized at build time.</p>

    <div class="card">
        <h2>Horizontal Image (横屏)</h2>
        <!-- src replacement -->
        <img src="https://random:h" alt="Loading random horizontal image..." />
        <br><br>
        
        <p>Complex Inline Style (CSS Variables):</p>
        <!-- Complex Inline Style Replacement -->
        <div style="--bannerOffset: 15vh;--banner-height-home: 65vh;--banner-height: 35vh;--configHue: 361;--page-width: 75rem;--bg-url: url(https://random:h);--bg-enable: 1;--bg-position: center;--bg-size: cover;--bg-repeat: no-repeat;--bg-attachment: fixed;--bg-opacity: 0.5; width: 100%; height: 200px; background-image: var(--bg-url); background-size: cover;">
            Complex Inline Style Box
        </div>
        <br><br>

        <p>CSS Variable defined in &lt;style&gt; tag:</p>
        <div class="css-var-box">
            CSS Variable Box
        </div>
    </div>

    <div class="card">
        <h2>Vertical Image (竖屏)</h2>
        <!-- Text Node Replacement Example -->
        <p>Current Random URL: <strong>https://random:v</strong></p>
        
        <img src="https://random:v" alt="Loading random vertical image..." style="max-height: 400px;" />
    </div>

    <!-- Import the generated scripts -->
    <script src="random-h.js"></script>
    <script src="random-v.js"></script>
</body>
</html>`;
    fs.writeFileSync(path.join(DIST, 'index.html'), htmlContent);
    console.log('Created demo index.html in dist');
}

build();
